version: 1.0.{build}-{branch}

branches:
  only:
    - appveyor

platform: x64

matrix:
  fast_finish: true

configuration:
  - Release
  - Debug

skip_tags: true

image: Visual Studio 2017

shallow_clone: true
clone_depth: 5

init:
  - dir C:\Tools
  - vcpkg install pdal:%PLATFORM%-windows

environment:
  VCPKG_ROOT: C:\Tools\vcpkg
  TARGET_OS: windows

install:
  - set ARCH=%PLATFORM%
  - set BUILD_TYPE=%CONFIGURATION%
  - call make.bat

build_script:
  - echo "Built %PLATFORM%-%TARGET_OS%-%CONFIGURATION%"

test_script:
  - set GDAL_DATA=%VCPKG_ROOT%\installed\%PLATFORM%-%TARGET_OS%\share\gdal
  - set PROJ_LIB=%VCPKG_ROOT%\installed\%PLATFORM%-%TARGET_OS%\share\proj4
  - if exist "build\%ARCH%-%TARGET_OS%\test_pdalc.exe" "build\%ARCH%-%TARGET_OS%\test_pdalc.exe"
  - if exist "build\%ARCH%-%TARGET_OS%\test_pdalcd.exe" "build\%ARCH%-%TARGET_OS%\test_pdalcd.exe"

after_test:
  - if exist "build\%ARCH%-%TARGET_OS%\test_pdalc.exe" erase "build\%ARCH%-%TARGET_OS%\test_pdalc.exe"
  - if exist "build\%ARCH%-%TARGET_OS%\test_pdalcd.exe" erase "build\%ARCH%-%TARGET_OS%\test_pdalcd.exe"




