version: Build {build} ({branch} branch)

branches:
  only:
    - appveyor

platform: x64

matrix:
  fast_finish: true

configuration:
  - Release
  - Debug

skip_tags: true

image: Visual Studio 2017

shallow_clone: true
clone_depth: 5

cache:
  - C:\Tools\downloads
  - C:\Tools\vcpkg
  - C:\OSGeo4W64

environment:
  DOWNLOAD_DIR: C:\Tools\downloads
  OSGEO4W_ROOT: C:\OSGeo4W64
  PREFIX_PATH: '%OSGEO4W_ROOT%'
  TARGET_OS: windows
  BUILD_DIR: build\%ARCH%-%TARGET_OS%-osgeo4w # where make.bat generates the Visual Studio project

init:
  - mkdir %DOWNLOAD_DIR%
  - curl -fsS -o %DOWNLOAD_DIR%\osgeo4w-setup-x86_64.exe http://download.osgeo.org/osgeo4w/osgeo4w-setup-x86_64.exe

install:
  - echo . | %DOWNLOAD_DIR%\osgeo4w-setup-x86_64.exe --autoaccept --no-shortcuts --no-startmenu --no-desktop --quiet-mode --arch x86_64 --advanced --site http://download.osgeo.org/osgeo4w --packages pdal > NUL

build_script:
  - set ARCH=%PLATFORM%
  - set BUILD_TYPE=%CONFIGURATION%
  - call make.bat
  - echo "Built %PLATFORM%-%TARGET_OS%-%CONFIGURATION%"

test_script:
  # These environment variables allow PDAL to locate GDAL and proj4 configuration files
  - set GDAL_DATA=%OSGEO4W_ROOT%\share\gdal
  - set PROJ_LIB=%OSGEO4W_ROOT%\share\proj
  - set PATH=%PATH%;%OSGEO4W_ROOT%\bin
  - dir %BUILD_DIR%\bin\*

    # pdal-c appends "d" to debug binaries, so either test_pdalc.exe or test_pdalcd.exe should be present, not both
  - if exist "%BUILD_DIR%\bin\test_pdalc.exe" "%BUILD_DIR%\bin\test_pdalc.exe"
  - if exist "%BUILD_DIR%\bin\test_pdalcd.exe" "%BUILD_DIR%\bin\test_pdalcd.exe"

after_test:
  - if exist "%BUILD_DIR%\bin\test_pdalc.exe" erase "%BUILD_DIR%\bin\test_pdalc.exe"
  - if exist "%BUILD_DIR%\bin\test_pdalcd.exe" erase "%BUILD_DIR%\bin\test_pdalcd.exe"

